#Docker for opengate_core
#systemctl start docker
#login: docker login
#build: docker build -t tbaudier/cobra2026_challenge_preprocessing -f Dockerfile.
#push: docker push tbaudier/cobra2026_challenge_preprocessing
#run: docker run --rm -v $PWD:/home -v -v /export4:/export4 tbaudier/cobra2026_challenge_preprocessing /home/.github/workflows/run_test_opengate_castor.sh
#interactive: docker run -ti --rm -v $PWD:/home -v -v /export4:/export4 quay.io/pypa/manylinux_2_34_x86_64 /bin/bash

FROM quay.io/pypa/manylinux_2_34_x86_64
MAINTAINER Thomas Baudier <thomas.baudier@creatis.insa-lyon.fr>
#Install packages
RUN     yum install -y gcc wget git expat-devel fftw-devel qt6-qtbase-devel freeglut-devel libXmu-devel xerces-c-devel libXpm-devel libXft-devel xrootd-devel openssl-devel libuuid-devel \

#Create folder
    && cd /home/docker \
    && /opt/python/cp312-cp312/bin/pip install torch --index-url https://download.pytorch.org/whl/cpu \
    && /opt/python/cp312-cp312/bin/pip install --no-cache-dir -r requirements.txt \
    && /opt/python/cp312-cp312/bin/python run_preprocessing.py -c ./configs/clb_config.yaml -d 'cpu' -s 1

